- name: "Install rust toolchain"
  block:
    - name: "Download rustup-init"
      ansible.builtin.get_url:
        url: "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
        dest: "/tmp/rustup-init"
        mode: "a+x"

    - name: "Install rust toolchain using rustup-init"  # noqa no-changed-when
      ansible.builtin.command: "/tmp/rustup-init -y"
