- name: Install rust toolchain
  block:
    - name: Download rustup-init
      ansible.builtin.uri:
        url: https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
        dest: /tmp/rustup-init
        status_code: [200, 304]
        mode: a+x

    - name: Install rust toolchain using rustup-init
      ansible.builtin.shell: /tmp/rustup-init -y
