- name: "Install firefox"
  become: true
  vars:
    firefox_dir: "/opt/firefox"
  block:
    - name: "Create {{ firefox_dir }}"
      ansible.builtin.file:
        path: "{{ firefox_dir }}"
        state: "directory"
        mode: "0755"

    - name: "Download firefox archive"
      ansible.builtin.unarchive:
        src: "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
        dest: "{{ firefox_dir }}"
        creates: "{{ firefox_dir }}/firefox"
        remote_src: true
        extra_opts: ["--strip-components=1"]

    - name: "Create firefox desktop entry"
      ansible.builtin.template:
        src: "firefox.desktop.j2"
        dest: "/usr/share/applications/firefox.desktop"
        mode: "0644"
