- hosts: all
  become: True
  roles:
    - { role: base, tags: base  }
    - { role: chrome, tags: chrome }
    - { role: docker, tags: docker }
    - { role: dotfiles, tags: dotfiles }
    - { role: gimp, tags: gimp }
    - { role: go, tags: go }
    - { role: jetbrains, tags: jetbrains }
    - { role: kate, tags: kate }
    - { role: konsole, tags: konsole }
    - { role: misc, tags: misc }
    - { role: nemo, tags: nemo }
    - { role: neovim, tags: neovim }
    - { role: node, tags: node }
    - { role: obs, tags: obs }
    - { role: python, tags: python }
    - { role: ruby, tags: ruby }
    - { role: rust, tags: rust }
    - { role: slack, tags: slack }
    - { role: spotify, tags: spotify }
    - { role: system, tags: system }
    - { role: terraform, tags: terraform }
    - { role: virtualbox, tags: virtualbox }
    - { role: vlc, tags: vlc }
    - { role: vscode, tags: vscode }
    - { role: wrk, tags: wrk }
    - { role: zsh, tags: zsh }
