- hosts: all
  become: True
  roles:
    - base
    - chrome
    - docker
    - dotfiles
    - gimp
    - go
    - jetbrains
    - kate
    - konsole
    - misc
    - nemo
    - neovim
    - node
    - obs
    - python
    - rust
    - slack
    - spotify
    - system
    - virtualbox
    - vlc
    - vscode
    - wrk
    - zsh
