Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-20.04"

  config.ssh.username = "aleksa"
  config.ssh.password = "root"

  config.vm.synced_folder "..", "/personal-ansible"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end
end
