- name: Install Jetbrains toolbox app
  block:
    - name: Download toolbox app
      get_url:
        url: https://download-cf.jetbrains.com/toolbox/jetbrains-toolbox-1.17.7275.tar.gz
        dest: /tmp/toolbox.tar.gz
        mode: 0666

    - name: Untar tooblox app
      unarchive:
        src: /tmp/toolbox.tar.gz
        dest: "/home/{{ username }}"
        owner: "{{ username }}"
