- name: "Set up dotfiles"
  vars:
    dotfiles_dir: "{{ home }}/dotfiles"
  block:
    - name: "Pull dotfiles repo"
      ansible.builtin.git:
        repo: "https://github.com/AleksaC/dotfiles"
        dest: "{{ dotfiles_dir }}"

    - name: "Symlink .zshrc"
      ansible.builtin.file:
        src: "{{ home }}/dotfiles/.zshrc"
        dest: "{{ home }}/.zshrc"
        state: "link"

    - name: "Symlink .profile"
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/.profile"
        dest: "{{ item }}"
        state: "link"
        force: true
      loop:
        - "{{ home }}/.profile"
        - "{{ home }}/.zprofile"

    - name: "Symlink powerlevel 10k config"
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/.p10k.zsh"
        dest: "{{ home }}/.p10k.zsh"
        state: "link"

    - name: "Symlink pypirc"
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/.pypirc"
        dest: "{{ home }}/.pypirc"
        state: link

    - name: "Symlink pythonrc"
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/.pythonrc.py"
        dest: "{{ home }}/.pythonrc.py"
        state: "link"

    - name: "Symlink npmrc"
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/.npmrc"
        dest: "{{ home }}/.npmrc"
        state: "link"

    - name: "Symlink terraformrc"
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/.terraformrc"
        dest: "{{ home }}/.terraformrc"
        state: "link"

    - name: "Ensure ~/.config/nvim exists"
      ansible.builtin.file:
        name: "{{ home }}/.config/nvim"
        state: "directory"

    - name: "Symlink init.vim"
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/init.vim"
        dest: "{{ home }}/.config/nvim/init.vim"
        state: link

    - name: "Symlink .editorconfig"
      ansible.builtin.file:
        src: "{{ dotfiles_dir }}/.editorconfig"
        dest: "{{ home }}/.editorconfig"
        state: link
