- name: Download dotfiles
  become: false
  vars:
    home: /home/{{ ansible_user }}
  block:
    - name: Pull dotfiles repo
      git:
        repo: https://github.com/AleksaC/dotfiles
        dest: "{{ home }}/dotfiles"

    - name: Symlink .zshrc
      file:
        src: "{{ home }}/dotfiles/.zshrc"
        dest: "{{ home }}/.zshrc"
        state: link

    - name: Symlink .profile
      file:
        src: "{{ home }}/dotfiles/.profile"
        dest: "{{ home }}/.profile"
        state: link
        force: yes

    - name: Symlink powerlevel 10k config
      file:
        src: "{{ home }}/dotfiles/.p10k.zsh"
        dest: "{{ home }}/.p10k.zsh"
        state: link

    - name: Symlink pypirc
      file:
        src: "{{ home }}/dotfiles/.pypirc"
        dest: "{{ home }}/.pypirc"
        state: link

    - name: Symlink pythonrc
      file:
        src: "{{ home }}/dotfiles/.pythonrc.py"
        dest: "{{ home }}/.pythonrc.py"
        state: link

    - name: Ensure ~/.config/nvim exists
      become: false
      file:
        name: "{{ home }}/.config/nvim"
        state: directory

    - name: Symlink init.vim
      file:
        src: "{{ home }}/dotfiles/init.vim"
        dest: "{{ home }}/.config/nvim/init.vim"
        state: link

    - name: Symlink .editorconfig
      file:
        src: "{{ home }}/dotfiles/.editorconfig"
        dest: "{{ home }}/.editorconfig"
        state: link
