- name: "Install Visual Studio Code"
  become: true
  block:
    - name: "Install Visual Studio Code dependencies"
      ansible.builtin.apt:
        pkg:
          - "software-properties-common"
          - "apt-transport-https"

    - name: "Import the Microsoft GPG key"
      ansible.builtin.apt_key:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        state: "present"

    - name: "Add Visual Studio Code repository"
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch }}] https://packages.microsoft.com/repos/vscode stable main
        state: "present"
        mode: "0666"

    - name: "Install Visual Studio Code"
      ansible.builtin.apt:
        name: "code"
