- name: Install kate
  become: true
  ansible.builtin.apt:
    name: kate

- name: Make kate default editor for text
  become: true
  ansible.builtin.replace:
    path: /usr/share/applications/defaults.list
    regexp: org.gnome.gnome.desktop
    ansible.builtin.replace: org.kde.kate.desktop
