- name: Install dependencies for building python
  apt:
    pkg:
      - libbz2-dev
      - libc6-dev
      - libffi-dev
      - libgdbm-dev
      - liblzma-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - zlib1g-dev
      - tk-dev

- name: Install pyenv and change global python interpreter
  become: false
  vars:
    pyenv_root: /home/{{ ansible_user }}/.pyenv
  block:
    - name: Clone pyenv repo
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: ~/.pyenv

    - name: Install python3.8
      shell: >
        export PYENV_ROOT="{{ pyenv_root }}" PATH="{{ pyenv_root }}/bin:$PATH" &&
        pyenv install 3.8.5 -s

    - name: Change global python version
      shell: >
        export PYENV_ROOT="{{ pyenv_root }}" PATH="{{ pyenv_root }}/bin:$PATH" &&
        pyenv global 3.8.5

- name: Install poetry
  become: false
  block:
    - name: Download poetry installer
      get_url:
        url: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        dest: /tmp/get-poetry.py
        mode: 0666

    - name: Run poetry installer
      shell: python3 /tmp/get-poetry.py -y

- name: Install pipx and commonly used python CLIs
  become: false
  vars:
    pyenv_root: /home/{{ ansible_user }}/.pyenv
  block:
    - name: Install pipx
      shell: |
        export PYENV_ROOT="{{ pyenv_root }}" PATH="{{ pyenv_root }}/bin:$PATH"
        eval "$(pyenv init -)"
        python -m pip install --user pipx

    - name: Run pipx ensurepath
      shell: pipx ensurepath

    - name: Install pre-commit
      shell: pipx install pre-commit

    - name: Install tox
      shell: pipx install tox

    - name: Install black
      shell: pipx install black

    - name: Install flake8
      shell: pipx install flake8

    - name: Install isort
      shell: pipx install isort

    - name: Install mypy
      shell: pipx install mypy

    - name: Install aws-cli
      shell: pipx install awscli
