- name: Install openssl & zlib headers  # needed by pyenv to install python3.8
  apt:
    pkg:
      - libssl-dev
      - zlib1g-dev

- name: Install pyenv and change global python interpreter
  become: false
  vars:
    pyenv_root: /home/{{ ansible_user }}/.pyenv
  block:
    - name: Clone pyenv repo
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: ~/.pyenv

    - name: Install python3.8
      shell: >
        export PYENV_ROOT="{{ pyenv_root }}" PATH="{{ pyenv_root }}/bin:$PATH" &&
        pyenv install 3.8.1 -s

    - name: Change global python version
      shell: >
        export PYENV_ROOT="{{ pyenv_root }}" PATH="{{ pyenv_root }}/bin:$PATH" &&
        pyenv global 3.8.1

- name: Install poetry
  become: false
  block:
    - name: Download poetry installer
      get_url:
        url: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        dest: /tmp/get-poetry.py

    - name: Run poetry installer
      shell: python3 /tmp/get-poetry.py -y
