- name: Install Fira Code font
  become: true
  apt:
    name: fonts-firacode

- name: Install GNOME Tweak Tool
  become: true
  apt:
    name: gnome-tweak-tool

- name: Install dconf editor
  become: true
  apt:
    name: dconf-editor

- name: Move dock to bottom
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'BOTTOM'"
    state: present

- name: Center dock
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
    value: "false"
    state: present

- name: Enable autohide
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
    value: "false"
    state: present

- name: Enable autohide
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/autohide"
    value: "true"
    state: present

- name: Set dark theme
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Yaru-dark'"
    state: present

- name: Isolate workspaces in app switcher
  dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"
    state: present

- name: Isolate workspaces in dock
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/isolate-workspaces"
    value: "true"
    state: present
