- name: "Install Fira Code font"
  become: true
  ansible.builtin.apt:
    name: "fonts-firacode"

- name: "Install dconf editor"
  become: true
  ansible.builtin.apt:
    name: "dconf-editor"

- name: "Move dock to bottom"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'BOTTOM'"
    state: "present"

- name: "Center dock"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
    value: "false"
    state: "present"

- name: "Enable autohide"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
    value: "false"
    state: "present"

- name: "Enable autohide"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/autohide"
    value: "true"
    state: "present"

- name: "Set dark theme"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Yaru-dark'"
    state: "present"

- name: "Isolate workspaces in app switcher"
  community.general.dconf:
    key: "/org/gnome/shell/app-switcher/current-workspace-only"
    value: "true"
    state: "present"

- name: "Isolate workspaces in dock"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/isolate-workspaces"
    value: "true"
    state: "present"

- name: "Disable sudo password for {{ username }} user"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers"
    regexp: "^{{ username }} ALL=(ALL) NOPASSWD: ALL$"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
