- name: Install zsh
  become: true
  apt:
    name: zsh

- name: Make zsh default shell
  become: true
  user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: Install powerline fonts
  become: true
  apt:
    name: fonts-powerline

- name: Install and configure ohmyzsh
  block:
    - name: Install ohmyzsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh
        dest: "/home/{{ username }}/.oh-my-zsh"

    - name: Install zsh autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "/home/{{ username }}/.oh-my-zsh/plugins/zsh-autosuggestions"

    - name: Install powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1

    - name: Install zsh syntax highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "/home/{{ username }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
