- name: Install Spotify
  become: true
  block:
    - name: Add Spotify signing key
      apt_key:
        url: https://download.spotify.com/debian/pubkey.gpg
        state: present

    - name: Add Spotify repository
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
        mode: 0666

    - name: Install Spotify
      apt:
        name: spotify-client
