- name: Install command line utils xclip, jq, htop, bat, unrar, brotli, rlwrap
  become: true
  ansible.builtin.apt:
    pkg:
      - xclip
      - jq
      - htop
      - bat
      - unrar
      - brotli
      - rlwrap

- name: Install hyperfine
  become: true
  ansible.builtin.apt:
    deb: "https://github.com/sharkdp/hyperfine/releases/download/\
      v1.13.0/hyperfine_1.13.0_{{ arch }}.deb"

- name: Install traceroute
  become: true
  ansible.builtin.apt:
    name: traceroute

- name: Install socat
  become: true
  ansible.builtin.apt:
    name: socat

- name: Make sure ~/.local exists
  ansible.builtin.file:
    path: /home/{{ username }}/.local
    state: directory

- name: "Symlink batcat to bat if it's installed that way"
  vars:
    batcat_path: "/usr/bin/batcat"
  block:
    - name: "Check if batcat exists"
      ansible.builtin.stat:
        path: "{{ batcat_path }}"
      register: "batcat"

    - name: "Symlink batcat"
      when: "batcat.stat.exists"
      ansible.builtin.file:
        src: "{{ batcat_path }}"
        dest: "/home/{{ username }}/.local/bin/bat"
        state: "link"

- name: Install fzf
  block:
    - name: Clone fzf repo
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf
        dest: /home/{{ username }}/.fzf

    - name: Install fzf
      ansible.builtin.shell: /home/{{ username }}/.fzf/install

- name: Install exa
  ansible.builtin.shell: |
    PATH="$HOME/.cargo/bin:$PATH" cargo install exa

- name: Install wrk
  block:
    - name: Install wrk dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - build-essential
          - libssl-dev
          - git

    - name: Pull wrk repo
      ansible.builtin.git:
        repo: https://github.com/wg/wrk.git
        dest: /tmp/wrk

    - name: Make wrk binary
      make:
        chdir: /tmp/wrk

    - name: Move wrk binary to /usr/local/bin
      become: true
      ansible.builtin.copy:
        src: /tmp/wrk/wrk
        dest: /usr/local/bin/wrk
        mode: 0555

- name: Install lm-sensors
  become: true
  ansible.builtin.apt:
    name: lm-sensors

- name: Install Insomnia client
  become: true
  ansible.builtin.apt:
    deb: https://updates.insomnia.rest/downloads/ubuntu/latest?app=com.insomnia.app

- name: Install CopyQ
  become: true
  ansible.builtin.apt:
    name: copyq
