- name: Install command line utils xclip, jq, htop, bat, unrar, brotli, rlwrap
  become: true
  apt:
    pkg:
      - xclip
      - jq
      - htop
      - bat
      - unrar
      - brotli
      - rlwrap

- name: Install hyperfine
  become: true
  apt:
    deb: https://github.com/sharkdp/hyperfine/releases/download/v1.11.0/hyperfine_1.11.0_amd64.deb

- name: Install traceroute
  become: true
  apt:
    name: traceroute

- name: Install socat
  become: true
  apt:
    name: socat

- name: Make sure ~/.local exists
  file:
    path: /home/{{ username }}/.local
    state: directory

- name: Symlink batcat to bat if it's installed that way
  file:
    src: /usr/bin/batcat
    dest: /home/{{ username }}/.local/bin/bat
    state: link

- name: Install fzf
  block:
    - name: Clone fzf repo
      git:
        repo: https://github.com/junegunn/fzf
        dest: /home/{{ username }}/.fzf

    - name: Install fzf
      shell: /home/{{ username }}/.fzf/install

- name: Install exa
  shell: |
    PATH="$HOME/.cargo/bin:$PATH" cargo install exa

- name: Install wrk
  block:
    - name: Install wrk dependencies
      become: true
      apt:
        pkg:
          - build-essential
          - libssl-dev
          - git

    - name: Pull wrk repo
      git:
        repo: https://github.com/wg/wrk.git
        dest: /tmp/wrk

    - name: Make wrk binary
      make:
        chdir: /tmp/wrk

    - name: Move wrk binary to /usr/local/bin
      become: true
      copy:
        src: /tmp/wrk/wrk
        dest: /usr/local/bin/wrk
        mode: 0555

- name: Install lm-sensors
  become: true
  apt:
    name: lm-sensors

- name: Install Insomnia client
  become: true
  apt:
    deb: https://updates.insomnia.rest/downloads/ubuntu/latest?app=com.insomnia.app

- name: Install CopyQ
  become: true
  apt:
    name: copyq
