- name: "Configure git"
  vars:
    git_template_dir: "{{ home }}/.git-template"
  block:
    - name: "Set global git username"
      community.general.git_config:
        name: "user.name"
        scope: "global"
        value: "AleksaC"

    - name: "Set global git email"
      community.general.git_config:
        name: "user.email"
        scope: "global"
        value: "aleksacukovic1@gmail.com"

    - name: "Use rebase for pull by default"
      community.general.git_config:
        name: "pull.rebase"
        scope: "global"
        value: "true"

    - name: "Do authostash on rebase"
      community.general.git_config:
        name: "rebase.autoStash"
        scope: "global"
        value: "true"

    - name: "Add multiple git alias"
      community.general.git_config:
        name: "alias.git"
        scope: "global"
        value: "!git"

    - name: "Create git init template directory"
      ansible.builtin.file:
        name: "{{ item }}"
        state: "directory"
        mode: "0755"
      with_items:
        - "{{ git_template_dir }}"
        - "{{ git_template_dir }}/hooks"

    - name: "Set git init.templateDir"
      community.general.git_config:
        name: "init.templateDir"
        scope: "global"
        value: "{{ git_template_dir }}"

    - name: "Add pre-commit to init template"
      ansible.builtin.copy:
        src: "pre-commit"
        dest: "{{ git_template_dir }}/hooks"
        mode: "a+x"
