- name: "Install kubectl"
  vars:
    kubectl_version: "v1.22.4"
    kubectl_destination: "/usr/local/bin/kubectl"
  block:
    # Ansible should be able to get the checksum from the url in the get_url task
    # but for some reason it's throwing an error so this is a workaround
    - name: "Get kubectl checksum"
      ansible.builtin.uri:
        url: "https://dl.k8s.io/{{ kubectl_version }}/bin/linux/{{ arch }}/kubectl.sha256"
        return_content: true
      register: "checksum"

    - name: "Install kubectl"
      become: true
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/{{ arch }}/kubectl"
        dest: "{{ kubectl_destination }}"
        checksum: "sha256:{{ checksum.content }}"
        mode: "a+x"

- name: "Install helm"
  become: true
  block:
    - name: "Install apt-transport-https"
      ansible.builtin.apt:
        pkg:
          - "apt-transport-https"

    - name: "Add helm signing key"
      ansible.builtin.apt_key:
        url: "https://baltocdn.com/helm/signing.asc"
        state: "present"

    - name: "Add helm repository"
      ansible.builtin.apt_repository:
        repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
        state: "present"
        mode: "0666"

    - name: "Install helm"
      ansible.builtin.apt:
        pkg:
          - "helm"
