- name: "Install kubectl"
  vars:
    kubectl_version: "v1.22.4"
    kubectl_destination: "/usr/local/bin/kubectl"
  block:
    # Ansible should be able to get the checksum from the url in the get_url task
    # but for some reason it's throwing an error so this is a workaround
    - name: "Get kubectl checksum"
      ansible.builtin.uri:
        url: "https://dl.k8s.io/{{ kubectl_version }}/bin/linux/{{ arch }}/kubectl.sha256"
        return_content: true
      register: "checksum"

    - name: "Install kubectl"
      become: true
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/{{ arch }}/kubectl"
        dest: "{{ kubectl_destination }}"
        checksum: "sha256:{{ checksum.content }}"
        mode: "a+x"

- name: "Install helm"
  become: true
  vars:
    helm_apt_key_location: "/usr/share/keyrings/helm-archive-keyring.gpg"
  block:
    - name: "Install apt-transport-https"
      ansible.builtin.apt:
        name: "apt-transport-https"

    - name: "Add helm signing key"
      ansible.builtin.apt_key:
        url: "https://baltocdn.com/helm/signing.asc"
        state: "present"
        keyring: "{{ helm_apt_key_location }}"

    - name: "Add helm repository"
      ansible.builtin.apt_repository:
        repo: >-
          deb [signed-by={{ helm_apt_key_location }}]
          https://baltocdn.com/helm/stable/debian/
          all main
        state: "present"
        filename: "helm"

    - name: "Install helm"
      ansible.builtin.apt:
        pkg:
          - "helm"

- name: "Install kubectx"
  become: true
  vars:
    kubectx_version: "0.9.4"
  ansible.builtin.unarchive:
    src: "https://github.com/ahmetb/kubectx/releases/download/\
      v{{ kubectx_version }}/kubectx_v{{ kubectx_version }}_linux_{{ ansible_architecture }}.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true
    include: "kubectx"
    mode: "a+x"

- name: "Install kubens"
  become: true
  vars:
    kubens_version: "0.9.4"
  ansible.builtin.unarchive:
    src: "https://github.com/ahmetb/kubectx/releases/download/\
      v{{ kubens_version }}/kubens_v{{ kubens_version }}_linux_{{ ansible_architecture }}.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true
    include: "kubens"
    mode: "a+x"

- name: "Install stern"
  become: true
  vars:
    stern_version: "1.21.0"
  ansible.builtin.unarchive:
    src: "https://github.com/stern/stern/releases/download/\
      v{{ stern_version }}/stern_{{ stern_version }}_linux_{{ arch }}.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true
    include: "stern"
    mode: "a+x"

- name: "Install kind"
  become: true
  vars:
    kind_version: "v0.14.0"
    kind_destination: "/usr/local/bin/kind"
  ansible.builtin.get_url:
    url: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-{{ arch }}"
    dest: "{{ kind_destination }}"
    checksum: "sha256:https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-{{ arch }}.sha256sum"
    mode: "a+x"
