- name: Install Google Chrome
  become: true
  block:
    - name: Add Google signing key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome repository
      apt_repository:
        repo: >-
          deb [arch={{ arch }}]
          http://dl.google.com/linux/chrome/deb
          stable main
        state: present
        mode: 0666

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
