- name: "Install Virtualbox"
  become: true
  when: "arch == 'amd64'"
  ansible.builtin.apt:
    name: "virtualbox"

- name: "Install VirtualBox Extension Pack"
  become: true
  when: "arch == 'amd64'"
  block:
    - name: "Accept VirtualBox Extension Pack license"
      ansible.builtin.debconf:
        name: "virtualbox-ext-pack"
        question: "virtualbox-ext-pack/license"
        value: "true"
        vtype: "select"

    - name: "Install VirtualBox Extension Pack"
      ansible.builtin.apt:
        name: "virtualbox-ext-pack"
