- name: Install Virtualbox
  become: true
  when: arch == "amd64"
  block:
    - name: Add Oracle signing key
      ansible.builtin.apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Add VirtualBox repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian
          {{ ansible_distribution_release }} contrib
        state: present
        mode: 0666

    - name: Install VirtualBox
      ansible.builtin.apt:
        name: virtualbox-6.1

- name: Install VirtualBox Extension Pack
  become: true
  when: arch == "amd64"
  block:
    - name: Accept VirtualBox Extension Pack license
      ansible.builtin.systemd:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: "true"
        vtype: select

    - name: Install VirtualBox Extension Pack
      ansible.builtin.apt:
        name: virtualbox-ext-pack
