- name: Add Oracle signing key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Add VirtualBox repository
  apt_repository:
    repo: >
      deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian
      {{ ansible_distribution_release }} contrib
    state: present
    mode: 0666

- name: Install VirtualBox
  apt:
    name: virtualbox-6.1
