- name: Install go
  vars:
    go_version: "1.17.3"
  block:
    - name: Check if appropriate go is already installed
      register: installed_version
      ignore_errors: true
      command: go version

    - name: Download and unarchive go toolchain
      when: installed_version.rc == 0 and go_version not in installed_version.stdout
      become: true
      block:
        - name: Clear out previous installation
          file:
            path: /usr/local/go
            state: absent

        - name: Download go tar
          unarchive:
            src: "https://dl.google.com/go/go{{ go_version }}.linux-{{ arch }}.tar.gz"
            dest: /usr/local
            remote_src: true
