- name: Download go tar
  get_url:
    url: https://dl.google.com/go/go1.17.3.linux-amd64.tar.gz
    dest: /tmp/go.tar.gz
    checksum: sha256:550f9845451c0c94be679faf116291e7807a8d78b43149f9506c1b15eb89008c
    mode: 0666

- name: Untar to /usr/local
  become: true
  unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
    owner: root
