- name: Download go tar
  get_url:
    url: https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz
    dest: /tmp/go.tar.gz
    checksum: sha256:aed845e4185a0b2a3c3d5e1d0a35491702c55889192bb9c30e67a3de6849c067

- name: Untar to /usr/local
  unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
    owner: root
