- name: "Download terraform binary"
  become: true
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_{{ arch }}.zip"
    dest: "/usr/local/bin"
    remote_src: true
    mode: "a+x"
