# Set arch properly
- name: Download zipped terraform binary
  get_url:
    url: https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_{{ arch }}.zip
    dest: /tmp/terraform.zip

- name: Unzip terraform binary
  become: true
  unarchive:
    src: /tmp/terraform.zip
    dest: "/usr/local/bin"
    mode: 0555
