- name: "Install fnm"
  vars:
    fnm_version: "v1.31.0"
  block:
    - name: "Ensure ~/.fnm exists"
      ansible.builtin.file:
        name: "{{ home }}/.fnm"
        state: "directory"
        mode: "0755"

    - name: "Download and unarchive fnm binary"
      ansible.builtin.unarchive:
        src: "https://github.com/Schniz/fnm/releases/download/{{ fnm_version }}/fnm-linux.zip"
        dest: "{{ home }}/.fnm"
        remote_src: true
        mode: "a+x"

- name: "Install node 16.x"  # noqa no-changed-when
  ansible.builtin.shell: |
    set -e;
    export PATH="$HOME/.fnm:$PATH"
    eval "`fnm env`"
    fnm install 16.14.2

- name: "Install yarn"
  become: true
  block:
    - name: "Add yarn signing key"
      ansible.builtin.apt_key:
        url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
        state: "present"

    - name: "Add yarn repository"
      ansible.builtin.apt_repository:
        repo: "deb https://dl.yarnpkg.com/debian/ stable main"
        state: "present"
        mode: "0666"

    - name: "Install yarn"
      ansible.builtin.apt:
        name: "yarn"
        install_recommends: false
