- name: Install nvm
  become: false
  block:
    - name: Download nvm installer
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
        dest: /tmp
        mode: 0744

    - name: Install nvm
      shell: /tmp/install.sh

- name: Install node
  become: false
  shell: >
    export NVM_DIR=/home/{{ ansible_user }}/.nvm &&
    \. "$NVM_DIR/nvm.sh" &&
    nvm install 12.18.2

- name: Install system node 14.x
  block:
    - name: Add NodeSource signing key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource node 14.x repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_14.x {{ ansible_lsb.codename }} main
        filename: nodesource
        state: present

    - name: Add NodeSource node 14.x source repository
      apt_repository:
        repo: deb-src https://deb.nodesource.com/node_14.x {{ ansible_lsb.codename }} main
        filename: nodesource
        state: present

    - name: Install node
      apt:
        name:
          - nodejs
        update_cache: yes

- name: Install yarn
  block:
    - name: add yarn signing key
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: add yarn repository
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present
        mode: 0666

    - name: install yarn
      apt:
        name: yarn
        install_recommends: no

- name: Install gatsby cli
  become: false
  shell: |
    export NVM_DIR=/home/{{ ansible_user }}/.nvm
    \. "$NVM_DIR/nvm.sh"
    npm install -g gatsby-cli
