- name: Install nvm
  block:
    - name: Download nvm installer
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
        dest: /tmp
        mode: 0744

    - name: Install nvm
      ansible.builtin.shell: /tmp/install.sh

- name: Install node
  ansible.builtin.shell: >
    export NVM_DIR=/home/{{ username }}/.nvm &&
    \. "$NVM_DIR/nvm.sh" &&
    nvm install 12.18.2

- name: Install yarn
  become: true
  block:
    - name: add yarn signing key
      ansible.builtin.apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: add yarn repository
      ansible.builtin.apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        state: present
        mode: 0666

    - name: install yarn
      ansible.builtin.apt:
        name: yarn
        install_recommends: false
