- name: Install Docker
  become: true
  block:
    - name: Install Docker dependencies
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add Docker signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Get CPU architecture
      command: dpkg --print-architecture
      register: arch

    - name: Add Docker repository
      apt_repository:
        repo: >-
          deb [arch={{ arch.stdout }}] https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        mode: 0666

    - name: Install Docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io

- name: Create Docker group
  become: true
  group:
    name: docker
    state: present

- name: Add user to Docker group
  become: true
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Reset ssh connection
  meta:
    reset_connection

- name: Create cli-plugins directory
  file:
    name: "{{ home }}/.docker/cli-plugins"
    state: directory
    mode: 0775

- name: Install docker compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.1.0/\
      docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: "{{ home }}/.docker/cli-plugins/docker-compose"
    mode: a+x

- name: Add /etc/docker/daemon.json
  become: true
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
  notify:
    - "Restart docker service"
