- name: Install protoc
  block:
    - name: Download protoc release
      ansible.builtin.get_url:
        url: "https://github.com/protocolbuffers/protobuf/releases/download/\
          v3.12.4/protoc-3.12.4-linux-{{ ansible_architecture }}.zip"
        dest: /tmp/protoc.zip
        mode: 0666

    - name: Create directory where protoc will be unzipped
      ansible.builtin.file:
        path: /tmp/protoc
        state: directory

    - name: Unzip protoc binary
      ansible.builtin.unarchive:
        src: /tmp/protoc.zip
        dest: /tmp/protoc

    - name: Move protoc binary /usr/local/bin
      become: true
      ansible.builtin.copy:
        src: /tmp/protoc/bin/protoc
        dest: /usr/local/bin/protoc
        mode: 0555

- name: Install texlive
  become: true
  ansible.builtin.apt:
    pkg:
      - texlive
      - texlive-latex-extra
      - texlive-fonts-extra
