- name: Download protoc release
  become: false
  get_url:
    url: https://github.com/protocolbuffers/protobuf/releases/download/v3.12.4/protoc-3.12.4-linux-x86_64.zip
    dest: /tmp/protoc.zip
    mode: 0666

- name: Create directory where protoc will be unzipped
  become: false
  file:
    path: /tmp/protoc
    state: directory

- name: Unzip protoc binary
  become: false
  unarchive:
    src: /tmp/protoc.zip
    dest: /tmp/protoc

- name: Move protoc binary /usr/local/bin
  copy:
    src: /tmp/protoc/bin/protoc
    dest: /usr/local/bin/protoc
    mode: 0750

- name: Install Insomnia client
  apt:
    deb: https://updates.insomnia.rest/downloads/ubuntu/latest?app=com.insomnia.app

- name: Install texlive
  apt:
    pkg:
      - texlive
      - texlive-latex-extra
      - texlive-fonts-extra
