- name: Install wrk dependencies
  apt:
    pkg:
      - build-essential
      - libssl-dev
      - git

- name: Pull wrk repo
  git:
    repo: https://github.com/wg/wrk.git
    dest: /tmp/wrk

- name: Make wrk binary
  make:
    chdir: /tmp/wrk

- name: Move wrk binary to /usr/local/bin
  copy:
    src: /tmp/wrk/wrk
    dest: /usr/local/bin/wrk
    mode: 775
