- name: Install neovim
  become: true
  apt:
    name: neovim

- name: Install vim plugins
  block:
    - name: Create plug directory
      file:
        name: "/home/{{ username }}/.local/share/nvim/site/autoload/"
        state: directory
        recurse: yes

    - name: Install Plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "/home/{{ username }}/.local/share/nvim/site/autoload/"
        mode: 0666

    - name: Install neovim plugins
      shell: nvim +PlugInstall +qall --headless
